Use RandomUserDb;

CREATE TABLE RandomUsers
(
    gender                       VARCHAR(6)    NOT NULL PRIMARY KEY,
    nametitle                    VARCHAR(2)    NOT NULL,
    namefirst                    VARCHAR(9)    NOT NULL,
    namelast                     VARCHAR(4)    NOT NULL,
    locationstreetnumber         INTEGER       NOT NULL,
    locationstreetname           VARCHAR(24)   NOT NULL,
    locationcity                 VARCHAR(30)   NOT NULL,
    locationstate                VARCHAR(16)   NOT NULL,
    locationcountry              VARCHAR(6)    NOT NULL,
    locationpostcode             INTEGER       NOT NULL,
    locationcoordinateslatitude  NUMERIC(7, 4) NOT NULL,
    locationcoordinateslongitude NUMERIC(8, 4) NOT NULL,
    locationtimezoneoffset       VARCHAR(5)    NOT NULL,
    locationtimezonedescription  VARCHAR(22)   NOT NULL,
    email                        VARCHAR(26)   NOT NULL,
    loginuuid                    VARCHAR(36)   NOT NULL,
    loginusername                VARCHAR(14)   NOT NULL,
    loginpassword                VARCHAR(6)    NOT NULL,
    loginsalt                    VARCHAR(8)    NOT NULL,
    loginmd5                     VARCHAR(32)   NOT NULL,
    loginsha1                    VARCHAR(40)   NOT NULL,
    loginsha256                  VARCHAR(64)   NOT NULL,
    dobdate                      VARCHAR(24)   NOT NULL,
    dobage                       INTEGER       NOT NULL,
    registereddate               VARCHAR(24)   NOT NULL,
    registeredage                INTEGER       NOT NULL,
    phone                        VARCHAR(14)   NOT NULL,
    cell                         VARCHAR(14)   NOT NULL,
    idname                       VARCHAR(3)    NOT NULL,
    idvalue                      VARCHAR(15)   NOT NULL,
    picturelarge                 VARCHAR(48)   NOT NULL,
    picturemedium                VARCHAR(52)   NOT NULL,
    picturethumbnail             VARCHAR(54)   NOT NULL,
    nat                          VARCHAR(2)    NOT NULL
);

INSERT INTO RandomUsers(gender, nametitle, namefirst, namelast, locationstreetnumber, locationstreetname, locationcity,
                        locationstate, locationcountry, locationpostcode, locationcoordinateslatitude,
                        locationcoordinateslongitude, locationtimezoneoffset, locationtimezonedescription, email,
                        loginuuid, loginusername, loginpassword, loginsalt, loginmd5, loginsha1, loginsha256, dobdate,
                        dobage, registereddate, registeredage, phone, cell, idname, idvalue, picturelarge,
                        picturemedium, picturethumbnail, nat)
VALUES ('female', 'Ms', 'Florencia', 'Arce', 7055, 'Circuito San Luis Potosí', 'Campo Militar N. 37B (El Cabi)',
        'Ciudad de Mexico', 'Mexico', 83845, 29.9606, 110.2302, '+6:00', 'Almaty, Dhaka, Colombo',
        'florencia.arce@example.com', '60fcb613-d2d6-4292-af63-9e219cd04b79', 'bluemeercat930', 'ground', 'iYAhJl50',
        'a624292c43a99d48705a9c8c39d919a6', '167ba849e27b69d711401221200e89bbc250cd48',
        '55b8267dec88c7718d025f9ea51a15d73eb0816091c8fe26c367d0cd15a073ab', '1953-09-04T07:45:23.629Z', 71,
        '2004-08-16T01:33:12.841Z', 20, '(678) 037 4676', '(624) 288 6209', 'NSS', '33 50 92 4070 6',
        'https://randomuser.me/api/portraits/women/55.jpg', 'https://randomuser.me/api/portraits/med/women/55.jpg',
        'https://randomuser.me/api/portraits/thumb/women/55.jpg', 'MX');
