CREATE DATABASE [RandomUserDb]
    CONTAINMENT = NONE
    ON  PRIMARY
    ( NAME = N'RandomUserDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RandomUserDb.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
    LOG ON
    ( NAME = N'RandomUserDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RandomUserDb_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
    COLLATE Latin1_General_CI_AS
WITH LEDGER = OFF
GO
ALTER DATABASE [RandomUserDb] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [RandomUserDb] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [RandomUserDb] SET ANSI_NULLS OFF
GO
ALTER DATABASE [RandomUserDb] SET ANSI_PADDING OFF
GO
ALTER DATABASE [RandomUserDb] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [RandomUserDb] SET ARITHABORT OFF
GO
ALTER DATABASE [RandomUserDb] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [RandomUserDb] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [RandomUserDb] SET AUTO_CREATE_STATISTICS OFF
GO
ALTER DATABASE [RandomUserDb] SET AUTO_UPDATE_STATISTICS OFF
GO
ALTER DATABASE [RandomUserDb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [RandomUserDb] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [RandomUserDb] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [RandomUserDb] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [RandomUserDb] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [RandomUserDb] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [RandomUserDb] SET  DISABLE_BROKER
GO
ALTER DATABASE [RandomUserDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [RandomUserDb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [RandomUserDb] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [RandomUserDb] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [RandomUserDb] SET  READ_WRITE
GO
ALTER DATABASE [RandomUserDb] SET RECOVERY FULL
GO
ALTER DATABASE [RandomUserDb] SET  MULTI_USER
GO
ALTER DATABASE [RandomUserDb] SET PAGE_VERIFY TORN_PAGE_DETECTION
GO
ALTER DATABASE [RandomUserDb] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [RandomUserDb] SET DELAYED_DURABILITY = DISABLED
GO
USE [RandomUserDb]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [RandomUserDb] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
